#spring:
#  redis:
#    host: localhost
#    port: 6379
#  cloud:
#    gateway:
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 10
#            redis-rate-limiter.burstCapacity: 20
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: DEBUG
#        data:
#          redis: DEBUG
#
#
#
#
#
